[package]
name = "japanese-ledger"
version = "0.3.0"
edition.workspace = true
publish = false
rust-version.workspace = true

[dependencies]

[dev-dependencies]
rstest = { workspace = true }
rstest-bdd.workspace = true
rstest-bdd-macros.workspace = true
